---
- name: Read installed version
  command: "{{ node_exporter_binary }} --version"
  register: final_version
  changed_when: false

- name: Display installation details
  debug:
    msg:
      - "======================================"
      - "Node Exporter Installed Successfully"
      - "Path    : {{ node_exporter_binary }}"
      - "Version : {{ final_version.stdout_lines[0] }}"
      - "Service : {{ ansible_facts.services.get(node_exporter_service, {}).get('state', 'Not Installed') }}"
      - "======================================"

# - name: Gather service facts
#   service_facts:
# - name: List service names
#   debug:
#     msg: "{{ ansible_facts.services.keys() | list }}"
# - name: Display installation details
#   debug:
#     msg:
#       - "======================================"
#       - "Node Exporter Installed Successfully"
#       - "Path    : {{ node_exporter_binary }}"
#       - "Version : {{ final_version.stdout_lines[0] }}"
#       - "Service : {{ ansible_facts.services[node_exporter_service].state }}"
#       - "======================================"