---
- name: This Role will be used to install java versions 1.7,1.8 and 17 on ubuntu
  hosts: all
  become: true
  gather_facts: false
  vars_prompt:
  - name: java_version
    prompt: Please select versions( 1.7, 1.8, 17)
    private: no
  roles:
  - install-java-versions
