---
- name: "Create Simple User"
  include_tasks: create_user.yml
  when: user_type == '1'
- name: "User with sudo rights"
  include_tasks: user_with_sudo_rights.yml
  when: user_type == '2'
- name: "Reset User's password"
  include_tasks: reset_password.yml
  when: user_type == '3'
- name: "Delete User"
  include_tasks: delete_user.yml
  when: user_type == '4'
    #- include_tasks: create_user.yml
    #- include_tasks: user_with_sudo_rights.yml
    #- include_tasks: reset_password.yml
    #- include_tasks: delete_user.yml
# tasks file for linux-user-management
