---
#- name: Reset the password
#  user:
#    name: "{{ user_name }}"
#    password: "{{ user_password }}"
#- name: Generate hashed password
#  shell: "mkpasswd -m sha-512 {{ user_password }}"
#  register: hashed_password
#  changed_when: false
- name: Reset the password
  user:
    name: "{{ user_name }}"
    password: "{{ user_password }}"
    update_password: always
- name: Expire password
  command: "passwd -e '{{ user_name }}'"
